- name: Directories are created
  file:
    path: "{{ item.dir }}"
    mode: 0777
    recurse: yes
    state: directory
  with_items: "{{ configs }}"
  tags: [jenkins]

- name: Container is running
  docker:
    name: jenkins
    image: "jenkins:{{ jenkins_version }}"
    ports: 8080:8080
    volumes:
      - /data/jenkins:/var/jenkins_home
  register: container_result
  tags: [jenkins]

- pause: seconds=45
  when: container_result|changed
  tags: [jenkins]

- name: Configurations are present
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dir }}/{{ item.file }}"
    mode: "{{ item.mode }}"
  with_items: "{{ configs }}"
  register: configs_result
  tags: [jenkins]

- name: SSH directory is created
  file:
    path: /data/jenkins/.ssh/
    mode: 0777
    recurse: yes
    state: directory
  tags: [jenkins]

- name: SSH key copied
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0777
    remote_src: true
  with_items:
    - { src: '/home/{{ remote_user }}/.ssh/id_rsa', dest: '/data/jenkins/.ssh/id_rsa' }
    - { src: '/home/{{ remote_user }}/.ssh/id_rsa.pub', dest: '/data/jenkins/.ssh/id_rsa.pub' }
  tags: [jenkins]

- name: Plugins are installed
  shell: "curl -X POST \
    -d '<jenkins><install plugin=\"{{ item }}@latest\" /></jenkins>' \
    --header 'Content-Type: text/xml' \
    http://{{ ip }}:8080/pluginManager/installNecessaryPlugins"
  args:
    creates: /data/jenkins/plugins/{{ item }}
  with_items: "{{ plugins }}"
  register: plugins_result
  tags: [jenkins]

- wait_for:
    path: /data/jenkins/plugins/{{ item }}
  with_items: "{{ plugins }}"
  tags: [jenkins]

# Workaround to fix the bug in restarting containers from Ansible 2

- name: Container is stopped
  docker:
    name: jenkins
    image: "jenkins:{{ jenkins_version }}"
    state: stopped
  when: configs_result|changed or plugins_result|changed
  tags: [jenkins]

- name: Container is running
  docker:
    name: jenkins
    image: "jenkins:{{ jenkins_version }}"
    ports: 8080:8080
    volumes:
      - /data/jenkins:/var/jenkins_home
  when: configs_result|changed or plugins_result|changed
  tags: [jenkins]

- pause: seconds=30
  when: configs_result|changed or plugins_result|changed
  tags: [jenkins]

- name: Job directories are present
  file:
    path: "{{ home }}/jobs/{{ item.name }}"
    state: directory
    mode: 0777
  with_items: "{{ jobs }}"
  tags: [jenkins]

- name: Jobs are present
  template:
    src: "{{ item.src }}"
    dest: "{{ home }}/jobs/{{ item.name }}/config.xml"
    mode: 0777
  with_items: "{{ jobs }}"
  register: jobs_result
  tags: [jenkins]

- name: Jenkins is reloaded
  uri:
    url: http://{{ ip }}:8080/reload
    method: POST
    status_code: 200,302
  when: jobs_result|changed
  ignore_errors: yes
  tags: [jenkins]

- name: Scripts are present
  copy:
    src: scripts
    dest: /data
    mode: 0766
  tags: [jenkins]
