- hosts: localhost
  remote_user: "{{ remote_user }}"
  serial: 1
  vars:
    - docker_cfg_dest: /lib/systemd/system/docker.service
    - is_systemd: true
  roles:
    - common
    - docker
    - docker-compose
    - consul-template
    - registry
